# Generated by Django 5.2.7 on 2025-12-24 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                ("deleted_at", models.DateField(blank=True, null=True)),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                ("deleted_at", models.DateField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("about", models.TextField()),
                ("release_year", models.IntegerField()),
                ("poster", models.URLField(blank=True, null=True)),
                ("imdb_link", models.URLField(blank=True, null=True)),
                ("rt_link", models.URLField(blank=True, null=True)),
                ("crunchyroll", models.URLField(blank=True, null=True)),
                ("genres", models.ManyToManyField(to="project.genre")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                ("deleted_at", models.DateField(blank=True, null=True)),
                ("movie_name", models.CharField(max_length=255)),
                ("about", models.TextField(blank=True)),
                ("release_year", models.IntegerField(blank=True, null=True)),
                ("poster", models.URLField(blank=True, null=True)),
                ("imdb_link", models.URLField(blank=True, null=True)),
                ("rt_link", models.URLField(blank=True, null=True)),
                ("crunchyroll", models.URLField(blank=True, null=True)),
                ("genres", models.ManyToManyField(blank=True, to="project.genre")),
                (
                    "series",
                    models.ForeignKey(
                        blank=True,
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="movies",
                        to="project.series",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
