# Generated by Django 5.2.7 on 2025-12-24 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="genres",
            new_name="genre",
        ),
        migrations.RenameField(
            model_name="series",
            old_name="genres",
            new_name="genre",
        ),
        migrations.RemoveField(
            model_name="genre",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="genre",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="genre",
            name="updated_at",
        ),
    ]
