# Generated by Django 5.2.7 on 2025-12-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "project",
            "0002_rename_genres_movie_genre_rename_genres_series_genre_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="series",
            name="release_year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
