# Generated by Django 5.2.7 on 2025-12-26 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_alter_series_release_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="series",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movies",
                to="project.series",
            ),
        ),
    ]
