# Generated by Django 5.2.7 on 2025-12-27 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_alter_movie_series"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="netflix",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="prime_video",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="series",
            name="netflix",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="series",
            name="prime_video",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="series",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="movies",
                to="project.series",
            ),
        ),
    ]
