# Generated by Django 5.2.7 on 2025-12-27 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0005_movie_netflix_movie_prime_video_series_netflix_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="crunchyroll",
            new_name="tmdb",
        ),
        migrations.RenameField(
            model_name="series",
            old_name="crunchyroll",
            new_name="tmdb",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="netflix",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="prime_video",
        ),
        migrations.RemoveField(
            model_name="series",
            name="netflix",
        ),
        migrations.RemoveField(
            model_name="series",
            name="prime_video",
        ),
    ]
