# Generated by Django 5.2.7 on 2025-12-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0006_rename_crunchyroll_movie_tmdb_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="crunchyroll",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="series",
            name="crunchyroll",
            field=models.URLField(blank=True, null=True),
        ),
    ]
